version: '3.8'

services:
  sharq:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: sharq
    container_name: sharq-university
    env_file: .env.sharq
    ports:
      - "18081:8080"
    volumes:
      - /root/admission_files:/app/uploads
    networks:
      - shared-net

  bxu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: bxu
    container_name: bxu-university
    env_file: .env.bxu
    ports:
      - "18082:8080"
    volumes:
      - /root/admission_files:/app/uploads
    networks:
      - shared-net

networks:
  shared-net:
    external: true
