version: '3.8'

services:
  app_dev:
    build: sharq-university
    container_name: sharq-university
    env_file:
      - .env.sharq-university
    ports:
      - "18081:8080"
    networks:
      - shared-net
    restart: always
    volumes:
      - /root/admission_files:/app/uploads

  app_prod:
    build: bxu-university
    container_name: bxu-university
    env_file:
      - .env.bxu-university
    ports:
      - "18081:8081"
    networks:
      - shared-net
    restart: always
    volumes:
      - /root/admission_files:/app/uploads

networks:
  shared-net:
    external: true
