version: '3.8'

services:
  app_dev:
    build: sharq-university
    container_name: sharq-university-dev
    env_file:
      - .env
    ports:
      - "18081:8080"
    networks:
      - shared-net
    restart: always
    volumes:
      - /root/admission_dev_files:/app/uploads

  app_prod:
    build: bxu-university
    container_name: sharq-university-prod
    env_file:
      - .env.prod
    ports:
      - "18081:8081"
    networks:
      - shared-net
    restart: always
    volumes:
      - /root/admission_prod_files:/app/uploads

networks:
  shared-net:
    external: true
