version: '3.8'

services:
  app:
    container_name: sharq-university
    build:
      context: .         # Dockerfile shu papkada bo‘lsa
      dockerfile: Dockerfile
    env_file:
      - .env             # .env fayldan o'zgaruvchilarni oladi
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "18080:8080"
    volumes:
      - /root/admission_files:/app/uploads
    networks:
      - shared-net
    restart: always

networks:
  shared-net:
    external: true
